'use strict'

export function getBooks(isAdmin, toBuy) {
    const books = [];

    books.push({author: 'Dan Brown', serie: 'Robert  Langdon', book: 'Änglar och demoner', year: 2000, bought: 'FALSE'})
    books.push({author: 'Dan Brown', serie: 'Robert  Langdon', book: 'Da vinci koden', year: 2003, bought: 'FALSE'})
    books.push({author: 'Dan Brown', serie: 'Robert  Langdon', book: 'Den förlorade symbolen', year: 2009, bought: 'FALSE'})
    books.push({author: 'Dan Brown', serie: 'Robert  Langdon', book: 'Inferno ', year: 2013, bought: 'FALSE'})
    books.push({author: 'Jan Guillou', serie: 'Hamilton', book: 'Coq Rouge', year: 1986, bought: 'FALSE'})
    books.push({author: 'Jan Guillou', serie: 'Hamilton', book: 'Den demokratiske terroristen', year: 1987, bought: 'FALSE'})
    books.push({author: 'Jan Guillou', serie: 'Hamilton', book: 'I nationens intresse', year: 1988, bought: 'FALSE'})
    books.push({author: 'Jan Guillou', serie: 'Hamilton', book: 'Fiendens fiende (roman)', year: 1989, bought: 'FALSE'})
    books.push({author: 'Jan Guillou', serie: 'Hamilton', book: 'Den hedervärde mördaren', year: 1990, bought: 'FALSE'})
    books.push({author: 'Jan Guillou', serie: 'Hamilton', book: 'Vendetta', year: 1991, bought: 'FALSE'})
    books.push({author: 'Jan Guillou', serie: 'Hamilton', book: 'Ingen mans land', year: 1992, bought: 'FALSE'})
    books.push({author: 'Jan Guillou', serie: 'Hamilton', book: 'Den enda segern', year: 1993, bought: 'FALSE'})
    books.push({author: 'Jan Guillou', serie: 'Hamilton', book: 'I hennes majestäts tjänst', year: 1994, bought: 'FALSE'})
    books.push({author: 'Jan Guillou', serie: 'Hamilton', book: 'En medborgare höjd över varje misstanke', year: 1995, bought: 'FALSE'})
    books.push({author: 'Jan Guillou', serie: 'Hamilton', book: 'Hamlon', year: 1995, bought: 'FALSE'})
    books.push({author: 'Jan Guillou', serie: 'Hamilton', book: 'Madame Terror', year: 2006, bought: 'FALSE'})
    books.push({author: 'Jan Guillou', serie: 'Hamilton', book: 'Men inte om det gäller din dotter', year: 2008, bought: 'FALSE'})
    books.push({author: 'Mari Jungstedt', serie: 'Anders Knutas', book: 'Den du inte ser', year: 2003, bought: 'FALSE'})
    books.push({author: 'Mari Jungstedt', serie: 'Anders Knutas', book: 'I denna stilla natt', year: 2004, bought: 'TRUE'})
    books.push({author: 'Mari Jungstedt', serie: 'Anders Knutas', book: 'Den inre kretsen', year: 2005, bought: 'TRUE'})
    books.push({author: 'Mari Jungstedt', serie: 'Anders Knutas', book: 'Den döende dandyn', year: 2006, bought: 'FALSE'})
    books.push({author: 'Mari Jungstedt', serie: 'Anders Knutas', book: 'I denna ljuva sommartid', year: 2007, bought: 'TRUE'})
    books.push({author: 'Mari Jungstedt', serie: 'Anders Knutas', book: 'Den mörka ängeln', year: 2008, bought: 'TRUE'})
    books.push({author: 'Mari Jungstedt', serie: 'Anders Knutas', book: 'Den dubbla tystnaden', year: 2009, bought: 'TRUE'})
    books.push({author: 'Mari Jungstedt', serie: 'Anders Knutas', book: 'Den farliga leken', year: 2010, bought: 'FALSE'})
    books.push({author: 'Mari Jungstedt', serie: 'Anders Knutas', book: 'Det fjärde offret', year: 2011, bought: 'TRUE'})
    books.push({author: 'Mari Jungstedt', serie: 'Anders Knutas', book: 'Den sista akten', year: 2012, bought: 'FALSE'})
    books.push({author: 'Mari Jungstedt', serie: 'Anders Knutas', book: 'Du går inte ensam', year: 2013, bought: 'FALSE'})
    books.push({author: 'Mari Jungstedt', serie: 'Anders Knutas', book: 'Den man älskar', year: 2014, bought: 'FALSE'})
    books.push({author: 'Mari Jungstedt', serie: 'Anders Knutas', book: 'Det andra ansiktet', year: 2016, bought: 'FALSE'})
    books.push({author: 'Mari Jungstedt', serie: 'Anders Knutas', book: 'Ett mörker mitt ibland oss', year: 2018, bought: 'FALSE'})
    books.push({author: 'Mari Jungstedt', serie: 'Anders Knutas', book: 'Jag ser dig', year: 2019, bought: 'FALSE'})
    books.push({author: 'Mari Jungstedt', serie: 'Anders Knutas', book: 'Där den sista lampan lyser', year: 2021, bought: 'FALSE'})
    books.push({author: 'Mari Jungstedt', serie: 'Anders Knutas', book: 'Det slutna rummet', year: 2023, bought: 'FALSE'})
    books.push({author: 'Mari Jungstedt', serie: 'Anders Knutas', book: 'Den sista utposten', year: 2024, bought: 'FALSE'})
    books.push({author: 'Åsa Larsson', serie: 'Rebecka Martinsson', book: 'Solstorm', year: 2003, bought: 'TRUE'})
    books.push({author: 'Åsa Larsson', serie: 'Rebecka Martinsson', book: 'Det blod som spillts', year: 2004, bought: 'TRUE'})
    books.push({author: 'Åsa Larsson', serie: 'Rebecka Martinsson', book: 'Svart stig', year: 2006, bought: 'FALSE'})
    books.push({author: 'Åsa Larsson', serie: 'Rebecka Martinsson', book: 'Till dess din vrede upphör', year: 2008, bought: 'FALSE'})
    books.push({author: 'Åsa Larsson', serie: 'Rebecka Martinsson', book: 'Till offer åt Molok', year: 2012, bought: 'FALSE'})
    books.push({author: 'Åsa Larsson', serie: 'Rebecka Martinsson', book: 'Fädernas missgärningar', year: 2021, bought: 'FALSE'})
    books.push({author: 'Camilla Läckberg', serie: 'Fjällbacka', book: 'Isprinsessan', year: 2003, bought: 'FALSE'})
    books.push({author: 'Camilla Läckberg', serie: 'Fjällbacka', book: 'Predikanten', year: 2004, bought: 'FALSE'})
    books.push({author: 'Camilla Läckberg', serie: 'Fjällbacka', book: 'Stenhuggaren', year: 2005, bought: 'FALSE'})
    books.push({author: 'Camilla Läckberg', serie: 'Fjällbacka', book: 'Olycksfågeln', year: 2006, bought: 'FALSE'})
    books.push({author: 'Camilla Läckberg', serie: 'Fjällbacka', book: 'Tyskungen', year: 2007, bought: 'FALSE'})
    books.push({author: 'Camilla Läckberg', serie: 'Fjällbacka', book: 'Sjöjungfrun', year: 2008, bought: 'FALSE'})
    books.push({author: 'Camilla Läckberg', serie: 'Fjällbacka', book: 'Fyrvaktaren', year: 2009, bought: 'FALSE'})
    books.push({author: 'Camilla Läckberg', serie: 'Fjällbacka', book: 'Änglamakerskan', year: 2011, bought: 'FALSE'})
    books.push({author: 'Camilla Läckberg', serie: 'Fjällbacka', book: 'Lejontämjaren', year: 2014, bought: 'FALSE'})
    books.push({author: 'Camilla Läckberg', serie: 'Fjällbacka', book: 'Häxan', year: 2017, bought: 'FALSE'})
    books.push({author: 'Camilla Läckberg', serie: 'Fjällbacka', book: 'Gökungen', year: 2022, bought: 'FALSE'})
    books.push({author: 'Viveca Lärn', serie: 'Saltön', book: 'Midsommarvals, Hummerfesten', year: 1999, bought: 'TRUE'})
    books.push({author: 'Viveca Lärn', serie: 'Saltön', book: 'En fröjdefull jul', year: 2001, bought: 'FALSE'})
    books.push({author: 'Viveca Lärn', serie: 'Saltön', book: 'Sol och vår', year: 2002, bought: 'FALSE'})
    books.push({author: 'Viveca Lärn', serie: 'Saltön', book: 'Saltön', year: 2005, bought: 'FALSE'})
    books.push({author: 'Viveca Lärn', serie: 'Saltön', book: 'Värmebölja', year: 2007, bought: 'FALSE'})
    books.push({author: 'Viveca Lärn', serie: 'Saltön', book: 'Aprilväder', year: 2008, bought: 'FALSE'})
    books.push({author: 'Viveca Lärn', serie: 'Saltön', book: 'Södra vägen till Saltön', year: 2014, bought: 'FALSE'})
    books.push({author: 'Viveca Lärn', serie: 'Saltön', book: 'Halta Hönans hotell', year: 2016, bought: 'FALSE'})
    books.push({author: 'Henning Mankell', serie: 'Kurt Wallander', book: 'Mördare utan ansikte', year: 1991, bought: 'TRUE'})
    books.push({author: 'Henning Mankell', serie: 'Kurt Wallander', book: 'Hundarna i Riga', year: 1992, bought: 'TRUE'})
    books.push({author: 'Henning Mankell', serie: 'Kurt Wallander', book: 'Den vita lejoninnan', year: 1993, bought: 'TRUE'})
    books.push({author: 'Henning Mankell', serie: 'Kurt Wallander', book: 'Mannen som log', year: 1994, bought: 'TRUE'})
    books.push({author: 'Henning Mankell', serie: 'Kurt Wallander', book: 'Villospår', year: 1995, bought: 'TRUE'})
    books.push({author: 'Henning Mankell', serie: 'Kurt Wallander', book: 'Den femte kvinnan', year: 1996, bought: 'TRUE'})
    books.push({author: 'Henning Mankell', serie: 'Kurt Wallander', book: 'Steget efter', year: 1997, bought: 'TRUE'})
    books.push({author: 'Henning Mankell', serie: 'Kurt Wallander', book: 'Brandvägg', year: 1998, bought: 'TRUE'})
    books.push({author: 'Henning Mankell', serie: 'Kurt Wallander', book: 'Pyramiden', year: 1999, bought: 'TRUE'})
    books.push({author: 'Henning Mankell', serie: 'Kurt Wallander', book: 'Innan frosten', year: 2002, bought: 'TRUE'})
    books.push({author: 'Henning Mankell', serie: 'Kurt Wallander', book: 'Den orolige mannen', year: 2009, bought: 'TRUE'})
    books.push({author: 'Henning Mankell', serie: 'Kurt Wallander', book: 'Handen', year: 2013, bought: 'FALSE'})
    books.push({author: 'Liza Marklund', serie: 'Annika Bengtzon', book: 'Sprängaren', year: 1998, bought: 'TRUE'})
    books.push({author: 'Liza Marklund', serie: 'Annika Bengtzon', book: 'Studio sex', year: 1999, bought: 'TRUE'})
    books.push({author: 'Liza Marklund', serie: 'Annika Bengtzon', book: 'Paradiset', year: 2000, bought: 'TRUE'})
    books.push({author: 'Liza Marklund', serie: 'Annika Bengtzon', book: 'Prime time', year: 2002, bought: 'TRUE'})
    books.push({author: 'Liza Marklund', serie: 'Annika Bengtzon', book: 'Den röda vargen', year: 2003, bought: 'TRUE'})
    books.push({author: 'Liza Marklund', serie: 'Annika Bengtzon', book: 'Nobels testamente', year: 2006, bought: 'TRUE'})
    books.push({author: 'Liza Marklund', serie: 'Annika Bengtzon', book: 'Livstid', year: 2007, bought: 'TRUE'})
    books.push({author: 'Liza Marklund', serie: 'Annika Bengtzon', book: 'En plats i solen', year: 2008, bought: 'TRUE'})
    books.push({author: 'Liza Marklund', serie: 'Annika Bengtzon', book: 'Du gamla du fria', year: 2011, bought: 'TRUE'})
    books.push({author: 'Liza Marklund', serie: 'Annika Bengtzon', book: 'Lyckliga gatan', year: 2013, bought: 'FALSE'})
    books.push({author: 'Liza Marklund', serie: 'Annika Bengtzon', book: 'Järnblod', year: 2015, bought: 'FALSE'})
    books.push({author: 'Liza Marklund', serie: 'Stenträsk-triologin', book: 'Polcirkeln', year: 2021, bought: 'FALSE'})
    books.push({author: 'Liza Marklund', serie: 'Stenträsk-triologin', book: 'Kallmyren', year: 2022, bought: 'FALSE'})
    books.push({author: 'Liza Marklund', serie: 'Stenträsk-triologin', book: 'Stormberget', year: 2023, bought: 'FALSE'})
    books.push({author: 'Jo Nesbø', serie: 'Harry Hole', book: 'Fladdermusmannen', year: 2000, bought: 'FALSE'})
    books.push({author: 'Jo Nesbø', serie: 'Harry Hole', book: 'Rödhake', year: 2002, bought: 'FALSE'})
    books.push({author: 'Jo Nesbø', serie: 'Harry Hole', book: 'Nemesis', year: 2004, bought: 'FALSE'})
    books.push({author: 'Jo Nesbø', serie: 'Harry Hole', book: 'Djävulsstjärnan', year: 2004, bought: 'FALSE'})
    books.push({author: 'Jo Nesbø', serie: 'Harry Hole', book: 'Frälsaren', year: 2006, bought: 'FALSE'})
    books.push({author: 'Jo Nesbø', serie: 'Harry Hole', book: 'Kackerlackorna', year: 2007, bought: 'FALSE'})
    books.push({author: 'Jo Nesbø', serie: 'Harry Hole', book: 'Snömannen', year: 2008, bought: 'FALSE'})
    books.push({author: 'Jo Nesbø', serie: 'Harry Hole', book: 'Pansarhjärta', year: 2010, bought: 'FALSE'})
    books.push({author: 'Jo Nesbø', serie: 'Harry Hole', book: 'Gengångare', year: 2012, bought: 'FALSE'})
    books.push({author: 'Jo Nesbø', serie: 'Harry Hole', book: 'Polis', year: 2013, bought: 'FALSE'})
    books.push({author: 'Jo Nesbø', serie: 'Harry Hole', book: 'Törst', year: 2017, bought: 'FALSE'})
    books.push({author: 'Jo Nesbø', serie: 'Harry Hole', book: 'Kniv', year: 2019, bought: 'FALSE'})
    books.push({author: 'Jo Nesbø', serie: 'Harry Hole', book: 'Blodmåne', year: 2023, bought: 'FALSE'})
    books.push({author: 'Hjorth Rosenfeldt', serie: 'Sebastian Bergman', book: 'Det fördolda', year: 2010, bought: 'FALSE'})
    books.push({author: 'Hjorth Rosenfeldt', serie: 'Sebastian Bergman', book: 'Lärjungen', year: 2011, bought: 'FALSE'})
    books.push({author: 'Hjorth Rosenfeldt', serie: 'Sebastian Bergman', book: 'Fjällgraven', year: 2012, bought: 'FALSE'})
    books.push({author: 'Hjorth Rosenfeldt', serie: 'Sebastian Bergman', book: 'Den stumma flickan', year: 2014, bought: 'FALSE'})
    books.push({author: 'Hjorth Rosenfeldt', serie: 'Sebastian Bergman', book: 'De underkända', year: 2015, bought: 'FALSE'})
    books.push({author: 'Hjorth Rosenfeldt', serie: 'Sebastian Bergman', book: 'En högre rättvisa', year: 2018, bought: 'FALSE'})
    books.push({author: 'Hjorth Rosenfeldt', serie: 'Sebastian Bergman', book: 'Som man sår', year: 2021, bought: 'FALSE'})
    books.push({author: 'Hjorth Rosenfeldt', serie: 'Sebastian Bergman', book: 'Skulden man bär', year: 2023, bought: 'FALSE'})
    books.push({author: 'Viveca Sten', serie: 'Sandhamn', book: 'I de lugnaste vatten', year: 2008, bought: 'FALSE'})
    books.push({author: 'Viveca Sten', serie: 'Sandhamn', book: 'I den innersta kretsen', year: 2009, bought: 'FALSE'})
    books.push({author: 'Viveca Sten', serie: 'Sandhamn', book: 'I grunden utan skuld', year: 2010, bought: 'FALSE'})
    books.push({author: 'Viveca Sten', serie: 'Sandhamn', book: 'I natt är du död', year: 2011, bought: 'FALSE'})
    books.push({author: 'Viveca Sten', serie: 'Sandhamn', book: 'I stundens hetta', year: 2012, bought: 'FALSE'})
    books.push({author: 'Viveca Sten', serie: 'Sandhamn', book: 'I farans riktning', year: 2013, bought: 'FALSE'})
    books.push({author: 'Viveca Sten', serie: 'Sandhamn', book: 'I maktens skugga', year: 2014, bought: 'FALSE'})
    books.push({author: 'Viveca Sten', serie: 'Sandhamn', book: 'I sanningens namn', year: 2015, bought: 'FALSE'})
    books.push({author: 'Viveca Sten', serie: 'Sandhamn', book: 'Iskalla ögonblick', year: 2017, bought: 'FALSE'})
    books.push({author: 'Viveca Sten', serie: 'Sandhamn', book: 'I fel sällskap', year: 2018, bought: 'FALSE'})
    books.push({author: 'Viveca Sten', serie: 'Sandhamn', book: 'I hemlighet begravd', year: 2019, bought: 'FALSE'})
    books.push({author: 'Övriga', serie: 'Jonas Jonasson', book: 'Hundraåringen som klev ut ...', year: 2021, bought: 'TRUE'})
    books.push({author: 'Övriga', serie: 'Katarina Mazetti', book: 'Grabben i graven bredvid', year: 2002, bought: 'TRUE'})
    books.push({author: 'Övriga', serie: 'Katarina Mazetti', book: 'Familjegraven', year: 2008, bought: 'TRUE'})

    if(toBuy)           { return books.filter(book => book.bought === 'FALSE'); }
     //else if (!isAdmin) { return books.filter(book => book.bought === 'TRUE'); }
     else               { return books}
}

